import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer, ToastProvider } from "@/components/Toast";
import { MessageDialogProvider } from "@/components/MessageDialog";
import { PaywallProvider } from "@/components/pay/Paywall";
import { SpeedInsights } from "@vercel/speed-insights/next";

export const metadata: Metadata = {
  title: "Stylesnap AI | Ghibli Art AI Photo Generator",
  description:
    "Transform your photos into magical Ghibli-style artwork instantly with StyleSnap AI. No signup required. Try the trending Ghibli art photo style transfer, upload your photo, and download high-quality Ghibli-inspired images for free!",
  openGraph: {
    title: "Stylesnap AI | Ghibli Art AI Photo Generator",
    description:
      "Transform your photos into magical Ghibli-style artwork instantly with StyleSnap AI. No signup required. Try the trending Ghibli art photo style transfer, upload your photo, and download high-quality Ghibli-inspired images for free!",
    url: "https://stylesnap-ai.vercel.app/",
    siteName: "StyleSnap AI",
    images: [
      {
        url: "https://stylesnap-ai.vercel.app/app.png",
        width: 1200,
        height: 630,
        alt: "Ghibli Art AI Photo Generator - StyleSnap AI",
        type: "image/png",
      },
      {
        url: "https://stylesnap-ai.vercel.app/icon-192.png",
        width: 192,
        height: 192,
        alt: "StyleSnap AI App Icon 192x192",
        type: "image/png",
      },
      {
        url: "https://stylesnap-ai.vercel.app/icon-512.png",
        width: 512,
        height: 512,
        alt: "StyleSnap AI App Icon 512x512",
        type: "image/png",
      },
    ],
    type: "website",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "Stylesnap AI | Ghibli Art AI Photo Generator",
    description:
      "Transform your photos into magical Ghibli-style artwork instantly with StyleSnap AI. No signup required. Try the trending Ghibli art photo style transfer, upload your photo, and download high-quality Ghibli-inspired images for free!",
    images: [
      "https://stylesnap-ai.vercel.app/app.png",
      "https://stylesnap-ai.vercel.app/icon-192.png",
      "https://stylesnap-ai.vercel.app/icon-512.png",
    ],
    site: "@StyleSnapAI",
    creator: "@StyleSnapAI",
  },
  metadataBase: new URL("https://stylesnap-ai.vercel.app/"),
  icons: {
    icon: [
      { url: "/logo.svg", type: "image/svg+xml" },
      { url: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    shortcut: "/logo.svg",
    apple: [
      { url: "/logo.svg", sizes: "any", type: "image/svg+xml" },
      { url: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { url: "/icon-512.png", sizes: "512x512", type: "image/png" },
    ],
    // PWA maskable icon
    other: [{ url: "/icon-192.png", rel: "mask-icon", color: "#000000" }],
  },
  manifest: "/site.webmanifest",
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      "max-snippet": -1,
      "max-image-preview": "large",
      "max-video-preview": -1,
    },
  },
  applicationName: "StyleSnap AI",
  generator: "Next.js",
  keywords: [
    // Brand and name related
    "StyleSnap AI",
    "Snaptyle",
    "Style Snap",
    "Snaptyle AI",
    "StyleSnapAI",
    "Snaptyle Art",
    "Snaptyle Generator",
    "Snaptyle Photo",
    "Snaptyle Style",
    "Snaptyle Anime",
    "Snaptyle Ghibli",
    "Snaptyle AI Generator",
    "Snaptyle AI Art",
    "Snaptyle AI Photo",
    "Snaptyle AI Style",
    "Snaptyle AI Editor",
    "Snaptyle AI Download",
    "Snaptyle AI Instagram",
    "Snaptyle AI Twitter",
    "Snaptyle AI Facebook",
    "Snaptyle AI Social Media",
    // Ghibli and Studio Ghibli
    "Ghibli Art",
    "Ghibli Style",
    "Ghibli AI",
    "Ghibli AI Generator",
    "Ghibli Art Generator",
    "Ghibli Style Transfer",
    "Ghibli Photo",
    "Ghibli Art Online",
    "Ghibli Art Free",
    "Ghibli Art Download",
    "Ghibli Art Instagram",
    "Ghibli Art Twitter",
    "Ghibli Art LinkedIn",
    "Ghibli Art WhatsApp",
    "Ghibli Art Facebook",
    "Ghibli Art Social Media",
    "Studio Ghibli",
    "Studio Ghibli Style",
    "Studio Ghibli Art",
    "Studio Ghibli AI",
    // General AI and photo
    "AI Photo Generator",
    "AI Art",
    "AI Image Generator",
    "AI Ghibli",
    "AI Ghibli Art",
    "AI Ghibli Photo",
    "AI Anime",
    "AI Anime Art",
    "AI Anime Generator",
    "AI Style Transfer",
    "AI Style Generator",
    "AI Art Generator",
    "AI Photo Editor",
    "AI Portrait Generator",
    "AI Portrait",
    "AI Drawing",
    "AI Illustration",
    "AI Cartoon",
    "AI Cartoon Generator",
    "AI Anime Portrait",
    "AI Anime Selfie",
    "AI Anime Filter",
    "AI Anime Style",
    "AI Anime Photo",
    "AI Anime Face",
    "AI Anime Maker",
    "AI Anime Avatar",
    "AI Anime Character",
    "AI Anime Selfie Generator",
    "AI Anime Art Generator",
    "AI Anime Image",
    "AI Anime Transformation",
    "AI Anime Conversion",
    "AI Anime Edit",
    "AI Anime Download",
    // Trending anime styles
    "Anime Style",
    "Anime Art",
    "Anime Photo",
    "Anime Generator",
    "Anime Filter",
    "Anime Portrait",
    "Anime Avatar",
    "Anime Character",
    "Anime Drawing",
    "Anime Illustration",
    "Anime Selfie",
    "Anime Face",
    "Anime Maker",
    "Anime Image",
    "Anime Transformation",
    "Anime Conversion",
    "Anime Edit",
    "Anime Download",
    "Anime Online",
    "Anime Free",
    "Anime Instagram",
    "Anime Twitter",
    "Anime Facebook",
    "Anime Social Media",
    // Trending anime and cartoon styles
    "One Piece Style",
    "Naruto Style",
    "Demon Slayer Style",
    "Jujutsu Kaisen Style",
    "Attack on Titan Style",
    "Chainsaw Man Style",
    "Spy x Family Style",
    "My Hero Academia Style",
    "Dragon Ball Style",
    "Sailor Moon Style",
    "Pokémon Style",
    "Bleach Style",
    "Death Note Style",
    "Mob Psycho 100 Style",
    "Tokyo Revengers Style",
    "Blue Lock Style",
    "Haikyuu Style",
    "JoJo Style",
    "JoJo's Bizarre Adventure Style",
    "Violet Evergarden Style",
    "Your Name Style",
    "Weathering With You Style",
    "Kimi no Na wa Style",
    "Suzume Style",
    "Howl's Moving Castle Style",
    "Totoro Style",
    "Princess Mononoke Style",
    "Spirited Away Style",
    "Kiki's Delivery Service Style",
    "Ponyo Style",
    "Castle in the Sky Style",
    "Akira Style",
    "Cyberpunk Anime Style",
    "Manga Style",
    "Manga Art",
    "Manga Generator",
    "Manga Photo",
    "Manga Portrait",
    "Manga Avatar",
    "Manga Character",
    "Manga Drawing",
    "Manga Illustration",
    "Cartoon Style",
    "Cartoon Art",
    "Cartoon Generator",
    "Cartoon Photo",
    "Cartoon Portrait",
    "Cartoon Avatar",
    "Cartoon Character",
    "Cartoon Drawing",
    "Cartoon Illustration",
    // General style and photo editing
    "Style Transfer",
    "Photo to Art",
    "Photo to Anime",
    "Photo to Cartoon",
    "Photo to Ghibli",
    "Photo to Drawing",
    "Photo to Illustration",
    "Photo to Painting",
    "Photo to Portrait",
    "Photo to Manga",
    "Photo to Avatar",
    "Photo Editor",
    "Photo Art Generator",
    "Photo Style Generator",
    "Photo Style Transfer",
    "Photo Style AI",
    "Photo Style Online",
    "Photo Style Free",
    "Photo Style Download",
    "Photo Style Instagram",
    "Photo Style Twitter",
    "Photo Style Facebook",
    "Photo Style Social Media",
    // Miscellaneous
    "Trending Anime Style",
    "Trending AI Art",
    "Trending AI Style",
    "Trending Anime Generator",
    "Trending Ghibli Style",
    "Trending Anime Art",
    "Trending Anime Photo",
    "Trending Anime Portrait",
    "Trending Anime Avatar",
    "Trending Anime Character",
    "Trending Anime Drawing",
    "Trending Anime Illustration",
    "Trending Anime Selfie",
    "Trending Anime Face",
    "Trending Anime Maker",
    "Trending Anime Image",
    "Trending Anime Transformation",
    "Trending Anime Conversion",
    "Trending Anime Edit",
    "Trending Anime Download",
    "Trending Anime Online",
    "Trending Anime Free",
    "Trending Anime Instagram",
    "Trending Anime Twitter",
    "Trending Anime Facebook",
    "Trending Anime Social Media",
  ],
  authors: [
    {
      name: "StyleSnap AI",
      url: "https://stylesnap-ai.vercel.app/",
    },
  ],
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ToastProvider>
          <PaywallProvider>
            <MessageDialogProvider>
              <ToastContainer />
              {children}
              <SpeedInsights />
            </MessageDialogProvider>
          </PaywallProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
