import type { Metadata } from "next";
import "./globals.css";
import { ToastContainer, ToastProvider } from "@/components/Toast";
import {
  MessageDialog,
  MessageDialogProvider,
} from "@/components/MessageDialog";
import { PaywallProvider } from "@/components/pay/Paywall";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`overscroll-none antialiased`}>
        <ToastProvider>
          <ToastContainer />
          <PaywallProvider>
            <MessageDialogProvider>{children}</MessageDialogProvider>
          </PaywallProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
